### ISSUE TITLE
Support recording modes

### ISSUE THREAD

**Issue by mpalmujoki** [pat/vcr_assistant#1]
I need to customize the VCR recording mode, i.e. how it works with plain VCR e.g. 

```
 VCR.use_cassette('paged_data', :record => :new_episodes) do
    result = message_history.fetch_message_lists()

    expect(result.length).to eq(1)
 end 
```

But I cannot find a way to pass on the parameters when using vcr_assistant.

**Comment by mpalmujoki** [comment]
Default cassette options helped me here

**Comment by pat** [comment]
Great to know you found a way forward, though custom options on a per-call basis would be useful! I shall look how to make that possible.

**Comment by pat** [comment]
Just pushed 0.2.0 which respects options for specific cassettes via d89977f1346fa487baaf4f8cf1e2ccba8acf5e1f:

``` ruby
assisted_cassette(example, :record => :new_episodes) do |assistant|
  # ...
end
```

**Comment by mpalmujoki** [comment]
Looks good! 👍
